# frozen_string_literal: true

require 'rails_helper'
require 'json'
require_relative '../../../app/models/concerns/plan_snapshot_checksum'
require_relative '../../support/mocks/plan_snapshot_values'

RSpec.describe PlanSnapshotChecksum do
  describe '.calculate' do
    let(:rda_json) { PlanSnapshotValues.mock_rda_json }
    let(:extension_json) { PlanSnapshotValues.mock_extension_json }

    it 'produces identical checksums for mock JSONs with different key order' do
      # Shuffle keys in the hashes (simulate reordering)
      rda_json_reordered = rda_json.deep_dup.sort_by { rand }.to_h
      extension_json_reordered = extension_json.deep_dup.sort_by { rand }.to_h

      # 1. Original hashes, as generated by the app
      checksum1 = described_class.calculate(rda_json, extension_json)

      # 2. Hashes with keys shuffled (simulating different key order)
      checksum2 = described_class.calculate(rda_json_reordered, extension_json_reordered)

      # 3. Hashes serialized to JSON strings (as might be stored in db)
      checksum3 = described_class.calculate(JSON.generate(rda_json), JSON.generate(extension_json))

      # 4. Shuffled hashes, then serialized to JSON strings (simulating both reordering and string input)
      checksum4 = described_class.calculate(JSON.generate(rda_json_reordered),
                                            JSON.generate(extension_json_reordered))

      expect(checksum1).to eq(checksum2)
      expect(checksum1).to eq(checksum3)
      expect(checksum1).to eq(checksum4)
    end

    it 'produces different checksums for different content' do
      altered = rda_json.deep_dup
      altered['dmp']['title'] = 'Changed Title'
      expect(described_class.calculate(rda_json,
                                       extension_json)).not_to eq(described_class.calculate(altered, extension_json))
    end

    context 'when serializers are called multiple times on an unchanged plan' do
      let(:plan) { create(:plan, start_date: nil, end_date: nil) }

      it 'produces the same checksum on repeated serialization calls' do
        checksum_one = PlanSnapshotChecksum.calculate(
          Api::V2::Serialization::RdaSerializer.call(plan: plan),
          Api::V2::Serialization::ExtensionSerializer.call(plan: plan)
        )
        checksum_two = PlanSnapshotChecksum.calculate(
          Api::V2::Serialization::RdaSerializer.call(plan: plan),
          Api::V2::Serialization::ExtensionSerializer.call(plan: plan)
        )

        expect(checksum_one).to eq(checksum_two)
      end
    end
  end

  describe '.normalize_json_for_checksum' do
    it 'returns a sorted JSON string for a hash with unordered keys' do
      unordered = { 'b' => 2, 'a' => 1, 'c' => { 'z' => 9, 'y' => 8 } }
      ordered_json = PlanSnapshotChecksum.send(:normalize_json_for_checksum, unordered)
      expect(ordered_json).to eq('{"a":1,"b":2,"c":{"y":8,"z":9}}')
    end

    it 'parses and sorts a JSON string input' do
      unordered = '{"b":2,"a":1,"c":{"z":9,"y":8}}'
      ordered_json = PlanSnapshotChecksum.send(:normalize_json_for_checksum, unordered)
      expect(ordered_json).to eq('{"a":1,"b":2,"c":{"y":8,"z":9}}')
    end
  end

  describe '.deep_sort' do
    it 'sorts hash keys recursively' do
      unordered = { 'b' => 2, 'a' => 1, 'c' => { 'z' => 9, 'y' => 8 } }
      sorted = PlanSnapshotChecksum.send(:deep_sort, unordered)
      expect(sorted.keys).to eq(%w[a b c])
      expect(sorted['c'].keys).to eq(%w[y z])
    end

    it 'preserves array order but sorts hashes inside arrays' do
      unordered = {
        'arr' => [
          { 'b' => 2, 'a' => 1, 'nums' => [3, 2, 1] },
          { 'd' => 4, 'c' => 3, 'nums' => [1, 2, 3] }
        ]
      }
      sorted = PlanSnapshotChecksum.send(:deep_sort, unordered)
      # Hash keys inside arrays are sorted
      expect(sorted['arr'][0].keys).to eq(%w[a b nums])
      expect(sorted['arr'][1].keys).to eq(%w[c d nums])
      # Array order is preserved (not sorted)
      expect(sorted['arr'][0]['nums']).to eq([3, 2, 1])
      expect(sorted['arr'][1]['nums']).to eq([1, 2, 3])
    end
  end
end
