FROM surnet/alpine-wkhtmltopdf:3.23.4-0.12.6-small AS wkhtmltopdf

FROM ruby:3.1.4-alpine AS builder

ENV INSTALL_PATH=/usr/src/app \
    RAILS_ENV=production \
    NODE_ENV=production \
    BUNDLE_WITHOUT='development:test:mysql:aws:sandbox:ci:wkhtmltopdf' \
    # Dummy values to enable `rake assets:precompile` without a real db
    DATABASE_URL=nulldb://nohost \
    SECRET_KEY_BASE=foo

# Create non-root user early
RUN addgroup -g 3000 -S dmpgroup && \
    adduser -u 1000 -S dmpuser -G dmpgroup

# - build-base && musl-dev: required for compiling native extensions
# - postgresql16-dev: required to compile pg gem
# - shared-mime-info:: required to compile mimemagic gem
# - tzdata: required to compile tzinfo gem
RUN apk update && apk add --no-cache \
    build-base \
    musl-dev \
    postgresql16-dev \
    git \
    nodejs=20.15.1-r0 \
    yarn \
    shared-mime-info \
    tzdata

WORKDIR $INSTALL_PATH

# For Bundler caching
COPY --chown=dmpuser:dmpgroup Gemfile* $INSTALL_PATH
RUN gem install bundler -v "$(tail -1 Gemfile.lock | tr -d " ")" && \
    bundle config set --local frozen 'true' && \
    # `deployment` flag installs gems to `vendor/bundle` directory
    # https://bundler.io/guides/deploying.html#deploying-your-application
    bundle config set --local deployment 'true' && \
    bundle install --jobs=3 --retry=3

# For Yarn caching
COPY --chown=dmpuser:dmpgroup package.json yarn.lock $INSTALL_PATH
RUN yarn install --prod --frozen-lockfile --check-files

COPY --chown=dmpuser:dmpgroup . $INSTALL_PATH

# Precompile assets as non-root user
# (tmp directory with correct permissions is required)
RUN mkdir -p $INSTALL_PATH/tmp && chown -R dmpuser:dmpgroup $INSTALL_PATH/tmp
USER dmpuser
RUN bundle exec rake assets:precompile

# Temporarily switch back to root user to delete /node_modules and tmp/*
USER root
RUN rm -rf ${INSTALL_PATH}/node_modules ${INSTALL_PATH}/tmp/*
USER dmpuser

FROM ruby:3.1.4-alpine AS app

ENV INSTALL_PATH=/usr/src/app

# Create non-root user with same UID/GID as builder
RUN addgroup -g 3000 -S dmpgroup && \
    adduser -u 1000 -S dmpuser -G dmpgroup

# - postgresql16-client: Required for pg gem to connect to PostgreSQL
# - imagemagick: Required for dragonfly gem to process images
# - libjpeg-turbo: Adds support for processing JPEG images
# - wget: Required for healthcheck
RUN apk update && apk add --no-cache \
    postgresql16-client \
    imagemagick \
    libjpeg-turbo \
    wget \
    nodejs=20.15.1-r0 \
    # Install dependencies for wkhtmltopdf
    # (See https://github.com/Surnet/docker-wkhtmltopdf/pkgs/container/alpine-wkhtmltopdf#other-images)
    libstdc++ \
    libx11 \
    libxrender \
    libxext \
    libssl3 \
    ca-certificates \
    fontconfig \
    freetype \
    ttf-dejavu \
    ttf-droid \
    ttf-freefont \
    ttf-liberation \
    # more fonts
  && apk add --no-cache --virtual .build-deps \
    msttcorefonts-installer \
  # Install microsoft fonts
  && update-ms-fonts \
  && fc-cache -f \
  # Clean up when done
  && rm -rf /tmp/* \
  && apk del .build-deps 

WORKDIR $INSTALL_PATH

# Copy wkhtmltopdf binary
COPY --from=wkhtmltopdf /bin/wkhtmltopdf /usr/bin/wkhtmltopdf
# Copy data for timezone and mime types from builder stage
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /usr/share/mime /usr/share/mime
# Copy application code from builder stage
COPY --from=builder --chown=dmpuser:dmpgroup $INSTALL_PATH $INSTALL_PATH

# Create required dirs, set ownerships, move + chmod entrypoint.sh
RUN mkdir -p ${INSTALL_PATH}/tmp/cache \
        ${INSTALL_PATH}/tmp/pids \
        ${INSTALL_PATH}/tmp/sockets \
        # Create env-specific directory for dragonfly datastore
        ${INSTALL_PATH}/public/system/dragonfly/${RAILS_ENV} \
        # For executing translation:sync
        ${INSTALL_PATH}/config/locale && \
    chown -R dmpuser:dmpgroup \
        ${INSTALL_PATH}/tmp \
        ${INSTALL_PATH}/public \
        ${INSTALL_PATH}/config/locale  && \
    chmod -R 755 \
        ${INSTALL_PATH}/tmp \
        ${INSTALL_PATH}/public \
        ${INSTALL_PATH}/config/locale && \
        # Move entrypoint.sh to /usr/bin/ (already copied from builder stage)
        mv ${INSTALL_PATH}/entrypoint.sh /usr/bin/entrypoint.sh && \
        # Make /usr/bin/entrypoint.sh executable
        chmod +x /usr/bin/entrypoint.sh

USER dmpuser

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
    CMD wget -qO- ${BASE_URL}/api/v1/heartbeat || exit 1

ENTRYPOINT ["/usr/bin/entrypoint.sh"]

# nginx stage to serve static assets
FROM nginx:1.31.2-alpine AS assets

ENV INSTALL_PATH=/usr/src/app

# Create non-root user
RUN addgroup -g 3000 -S dmpgroup && \
    adduser -u 1000 -S dmpuser -G dmpgroup && \
    # Create required nginx directories with correct permissions
    mkdir -p /var/cache/nginx /var/run && \
    chown -R dmpuser:dmpgroup /var/cache/nginx /var/run /etc/nginx

USER dmpuser

COPY --from=app --chown=dmpuser:dmpgroup ${INSTALL_PATH}/public/assets /usr/share/nginx/html/assets
COPY --chown=dmpuser:dmpgroup nginx.conf /etc/nginx/nginx.conf
COPY --chown=dmpuser:dmpgroup nginx.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
