ARG RUBY_VERSION=3.1.4-alpine
ARG NODE_VERSION=20.15.1-r0
ARG WKHTMLTOPDF_VERSION=3.21.2-0.12.6-small

FROM surnet/alpine-wkhtmltopdf:$WKHTMLTOPDF_VERSION AS wkhtmltopdf

FROM ruby:$RUBY_VERSION AS builder

ARG NODE_VERSION
ENV INSTALL_PATH=/usr/src/app \
    RAILS_ENV=production \
    NODE_ENV=production \
    BUNDLE_WITHOUT='development:test:mysql:aws:sandbox:ci:wkhtmltopdf' \
    # Dummy values to enable `rake assets:precompile` without a real db
    DATABASE_URL=nulldb://nohost \
    SECRET_KEY_BASE=foo

# - build-base && musl-dev: required for compiling native extensions
# - postgresql16-dev: required to compile pg gem
# - shared-mime-info:: required to compile mimemagic gem
# - tzdata: required to compile tzinfo gem
RUN apk update && apk add --no-cache \
    build-base \
    musl-dev \
    postgresql16-dev \
    git \
    nodejs=$NODE_VERSION \
    yarn \
    shared-mime-info \
    tzdata

WORKDIR $INSTALL_PATH

# For Bundler caching
COPY Gemfile* $INSTALL_PATH
RUN gem install bundler -v "$(tail -1 Gemfile.lock | tr -d " ")" && \
    bundle config set --local frozen 'true' && \
    # `deployment` flag installs gems to `vendor/bundle` directory
    # https://bundler.io/guides/deploying.html#deploying-your-application
    bundle config set --local deployment 'true' && \
    bundle install --jobs=3 --retry=3

# For Yarn caching
COPY package.json yarn.lock $INSTALL_PATH
RUN yarn install --prod --frozen-lockfile --check-files

COPY . $INSTALL_PATH

# Precompile assets within builder stage
RUN bundle exec rake assets:precompile && \
rm -rf ${INSTALL_PATH}/node_modules ${INSTALL_PATH}/tmp/*

FROM ruby:$RUBY_VERSION AS api

ARG NODE_VERSION
ARG BASE_URL
ENV INSTALL_PATH=/usr/src/app \
    HEALTHCHECK_URL=${BASE_URL}/api/v1/heartbeat

# - postgresql16-client: Required for pg gem to connect to PostgreSQL
# - imagemagick: Required for dragonfly gem to process images
# - libjpeg-turbo: Adds support for processing JPEG images
# - wget: Required for healthcheck
RUN apk update && apk add --no-cache \
    postgresql16-client \
    imagemagick \
    libjpeg-turbo \
    wget \
    nodejs=$NODE_VERSION \
    # Install dependencies for wkhtmltopdf
    # (See https://github.com/Surnet/docker-wkhtmltopdf/pkgs/container/alpine-wkhtmltopdf#other-images)
    libstdc++ \
    libx11 \
    libxrender \
    libxext \
    libssl3 \
    ca-certificates \
    fontconfig \
    freetype \
    ttf-dejavu \
    ttf-droid \
    ttf-freefont \
    ttf-liberation \
    # more fonts
  && apk add --no-cache --virtual .build-deps \
    msttcorefonts-installer \
  # Install microsoft fonts
  && update-ms-fonts \
  && fc-cache -f \
  # Clean up when done
  && rm -rf /tmp/* \
  && apk del .build-deps 

WORKDIR $INSTALL_PATH

# Copy wkhtmltopdf binary
COPY --from=wkhtmltopdf /bin/wkhtmltopdf /usr/bin/wkhtmltopdf
# Copy data for timezone and mime types
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /usr/share/mime /usr/share/mime
# Copy application code and dependencies from builder stage
COPY --from=builder $INSTALL_PATH $INSTALL_PATH

# Run container as non-root user
RUN addgroup -S dmpgroup && adduser -S dmpuser -G dmpgroup && \
    # Create env-specific directory for dragonfly datastore
    mkdir -p ${INSTALL_PATH}/public/system/dragonfly/${RAILS_ENV} && \
    # Update ownership of files that need to be writable during production runtime
    chown -R dmpuser:dmpgroup ${INSTALL_PATH}/tmp \
    ${INSTALL_PATH}/public/ \
    # For executing translation:sync
    ${INSTALL_PATH}/config/locale \
    ${INSTALL_PATH}/config/locales

USER dmpuser

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
    CMD wget -qO- $HEALTHCHECK_URL || exit 1


# nginx stage to serve static assets and proxy requests to api container
FROM nginx:alpine AS web

ARG SERVER_NAME

ENV SERVER_NAME=$SERVER_NAME \
    INSTALL_PATH=/usr/src/app

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=api ${INSTALL_PATH}/public/assets /usr/share/nginx/html/assets

# Perform envsubst substitution at runtime to set `server_name` value in nginx.conf
CMD envsubst '${SERVER_NAME}' < /etc/nginx/nginx.conf > /tmp/nginx.conf \
    # Using a temporary file ensures the configuration is fully generated before Nginx starts.
    && mv /tmp/nginx.conf /etc/nginx/nginx.conf \
    # Run Nginx in the foreground, allowing the Docker container to remain active.
    && nginx -g 'daemon off;'


EXPOSE 80