version: '3'
services:
  server:
    build:
      context: ./
    volumes:
      - ./:/usr/src/app:cached
      - ./config/branding.yml:/usr/src/app/config/branding.yml:cached
      - ../db_backups/:/tmp/dat/:cached
      - bundle:/bundle
    command: /usr/src/app/scripts/start.sh
    environment:
      DATABASE_URL: 'mysql2://db'
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - db

  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server

  db:
    image: postgres:15-alpine
    volumes:
      - db_volume:/var/lib/mysql
    env_file:
      - ./.env
volumes:
  db_volume:
  bundle:
