{{- if .Values.ingress.enabled -}}
{{- $fullName := include "dmp-roadmap.fullname" . -}}
{{- $hostname := include "dmp-roadmap.hostname" . -}}
{{- $appSvcName := printf "%s-app" $fullName -}}
{{- $appSvcPort := .Values.app.service.port -}}
{{- $assetsSvcName := printf "%s-assets" $fullName -}}
{{- $assetsSvcPort := .Values.assets.service.port -}}
{{- $annotations := .Values.ingress.annotations -}}
{{- $hosts := .Values.ingress.hosts -}}
{{- if not $hosts }}
  {{- $hosts = list (dict "host" $hostname "paths" (list (dict "path" "/" "pathType" "Prefix"))) -}}
{{- end }}
{{- if .Values.ingress.certManager.enabled }}
  {{- if .Values.ingress.certManager.issuer }}
    {{- $_ := set $annotations "cert-manager.io/issuer" .Values.ingress.certManager.issuer }}
  {{- end }}
  {{- if .Values.ingress.certManager.clusterIssuer }}
    {{- $_ := set $annotations "cert-manager.io/cluster-issuer" .Values.ingress.certManager.clusterIssuer }}
  {{- end }}
  {{- with .Values.ingress.certManager.annotations }}
    {{- $annotations = merge $annotations . }}
  {{- end }}
{{- end }}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey $annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set $annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- $_ := set . "component" "ingress" }}
    {{- include "dmp-roadmap.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.certManager.enabled }}
  tls:
    {{- if .Values.ingress.certManager.enabled }}
    {{- range $hosts }}
    - hosts:
        - {{ .host }}
      secretName: {{ $fullName }}-tls
    {{- end }}
    {{- else }}
    {{- with .Values.ingress.tls }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $hosts }}
    - host: {{ .host }}
      http:
        paths:
          # Route to assets deployment for /assets
          - path: /assets
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $assetsSvcName }}
                port:
                  number: {{ $assetsSvcPort }}
              {{- else }}
              serviceName: {{ $assetsSvcName }}
              servicePort: {{ $assetsSvcPort }}
              {{- end }}
          {{- range .paths }}
          # Route configured paths to the app
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $appSvcName }}
                port:
                  number: {{ $appSvcPort }}
              {{- else }}
              serviceName: {{ $appSvcName }}
              servicePort: {{ $appSvcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
