# frozen_string_literal: true

module Api
  module V2
    class PlansController < BaseApiController # rubocop:todo Style/Documentation
      respond_to :json
      before_action :set_complete_param, only: %i[show index]

      # If the Resource Owner (aka User) is in the Doorkeeper AccessToken then it is an authorization_code
      # token and we need to ensure that the ApiClient is authorized for the relevant Scope
      before_action -> { doorkeeper_authorize! :write }, only: %i[create update]
      before_action :require_read_scope, only: %i[index show]

      # GET /api/v2/plans/:id
      def show
        @plan = plans_scope.find_by(id: params[:id])

        plans_policy = PlansPolicy.new(@resource_owner, @plan)
        raise Pundit::NotAuthorizedError unless plans_policy.show?

        @items = [@plan]
        render '/api/v2/plans/index', status: :ok
      end

      # GET /api/v2/plans
      def index
        @plans = plans_scope
        @items = paginate_response(results: @plans)
        render '/api/v2/plans/index', status: :ok
      end

      # POST /api/v2/plans
      # rubocop:disable Metrics/AbcSize, Metrics/MethodLength,Lint/MissingCopEnableDirective
      # rubocop:disable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
      def create # rubocop:disable Metrics/AbcSize
        json = parsed_json
        return render_error(errors: [_('Invalid JSON')], status: :bad_request) unless json

        dmp = json.with_indifferent_access.fetch(:items, []).first.fetch(:dmp, {})

        # Do a pass through the raw JSON and check to make sure all required fields
        # were present. If not, return the specific errors
        errs = Api::V1::JsonValidationService.validation_errors(json: dmp)
        render_error(errors: errs, status: :bad_request) and return if errs.any?

        # Convert the JSON into a Plan and it's associations
        plan = Api::V1::Deserialization::Plan.deserialize(json: dmp)
        if plan.present?
          save_err = _('Unable to create your DMP')
          exists_err = _('Plan already exists. Send an update instead.')
          no_org_err = _("Could not determine ownership of the DMP. Please add an
                    :affiliation to the :contact")

          # Try to determine the Plan's owner
          owner = determine_owner(client: @resource_owner, plan: plan)
          plan.org = owner.org if owner.present? && plan.org.blank?
          render_error(errors: no_org_err, status: :bad_request) and return unless plan.org.present?

          # Validate the plan and it's associations and return errors with context
          # e.g. 'Contact affiliation name can't be blank' instead of 'name can't be blank'
          errs = Api::V1::ContextualErrorService.process_plan_errors(plan: plan)

          # The resulting plan (or its associations were invalid)
          render_error(errors: errs, status: :bad_request) and return if errs.any?

          # Skip if this is an existing DMP
          render_error(errors: exists_err, status: :bad_request) and return unless plan.new_record?

          # If we cannot save for some reason then return an error
          plan = Api::V1::PersistenceService.safe_save(plan: plan)
          render_error(errors: save_err, status: :internal_server_error) and return if plan.new_record?

          # If the plan was generated by an ApiClient then associate them
          plan.update(api_client_id: @resource_owner.id) if @resource_owner.is_a?(ApiClient)

          # Invite the Owner if they are a Contributor then attach the Owner to the Plan
          owner = invite_contributor(contributor: owner) if owner.is_a?(Contributor)
          plan.add_user!(owner.id, :creator)

          # Kaminari Pagination requires an ActiveRecord result set :/
          @items = paginate_response(results: Plan.where(id: plan.id))
          render '/api/v2/plans/index', status: :created
        else
          render_error(errors: [_('Invalid JSON!')], status: :bad_request)
        end
      rescue JSON::ParserError
        render_error(errors: [_('Invalid JSON')], status: :bad_request)
      end

      # PUT api/v2/plans/:id
      def update
        json = parsed_json
        return render_error(errors: ['Invalid JSON'], status: :bad_request) unless json

        plan = Plan.find_by(id: params[:id])
        return render_error(errors: ['Plan not found'], status: :not_found) unless plan

        plans_policy = PlansPolicy.new(@resource_owner, plan)
        raise Pundit::NotAuthorizedError unless plans_policy.update?

        answers_payload = json.with_indifferent_access[:answers]
        unless answers_payload.is_a?(Array)
          return render_error(errors: ['Missing answers payload'],
                              status: :bad_request)
        end

        errors = []

        answers_payload.each do |ans|
          question_id = ans[:question_id]
          text = ans[:text]

          question = Question.find_by(id: question_id)

          unless question && plan.template.questions.exists?(id: question_id)
            errors << "Question #{question_id} does not belong to this plan"
            next
          end

          answer = Answer.find_by(plan_id: plan.id, question_id: question_id)

          answer.text = text

          errors.concat(answer.errors.full_messages) unless answer.save
        end

        return render_error(errors: errors, status: :bad_request) if errors.any?

        @items = paginate_response(results: Plan.where(id: plan.id))
        render '/api/v2/plans/index', status: :ok
      end

      private

      # GET /api/v2/plans?complete=true and  /api/v2/plans/:id?complete=true
      def set_complete_param
        @complete = params[:complete].to_s.casecmp('true').zero?
      end

      def plans_scope
        scope = PlansPolicy::Scope.new(@resource_owner).resolve
        @complete ? scope.includes(answers: { question: :section }) : scope
      end

      def plan_exists?(json:)
        return false unless json.present? &&
                            json[:dmp_id].present? &&
                            json[:dmp_id][:identifier].present?

        scheme = IdentifierScheme.by_name(json[:dmp_id][:type]).first
        Identifier.exists?(value: json[:dmp_id][:identifier], identifier_scheme: scheme)
      end

      # Get the Plan's owner
      def determine_owner(client:, plan:)
        contact = plan.contributors.find(&:data_curation?)
        # Use the contact if it was sent in and has an affiliation defined
        return contact if contact.present? && contact.org.present?

        # If the contact has no affiliation defined, see if they are already a User
        user = lookup_user(contributor: contact)
        return user if user.present?

        # Otherwise just return the client
        client
      end

      def lookup_user(contributor:)
        return nil unless contributor

        identifiers = contributor.identifiers.map do |id|
          { name: id.identifier_scheme&.name, value: id.value }
        end

        user = User.from_identifiers(array: identifiers) if identifiers.any?
        user ||= User.find_by(email: contributor.email) unless user.present?
        user
      end

      def invite_contributor(contributor:)
        return nil unless contributor.present?

        # If the user was not found, invite them and attach any know identifiers
        names = contributor.name&.split || ['']
        firstname = names.length > 1 ? names.first : nil
        surname = names.length > 1 ? names.last : names.first
        user = User.invite!({ email: contributor.email,
                              firstname: firstname,
                              surname: surname,
                              org: contributor.org }, @resource_owner)

        contributor.identifiers.each do |id|
          user.identifiers << Identifier.new(
            identifier_scheme: id.identifier_scheme, value: id.value
          )
        end
        user
      end
      # rubocop:enable Metrics/AbcSize

      def parsed_json
        @parsed_json ||= JSON.parse(request.body.read)
      rescue JSON::ParserError
        nil
      end
    end
  end
end
