---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cephfs-locales-key
  namespace: dmp-roadmap-staging
spec:
  encryptedData:
    key: AgB9ZA0AddBxq0qPJmtHlazys25IwR12Z4C0f26dpLfeNGAvD9WTjgTrZWn1mTKQrJwZ2mVGuKgtud1GMV9IGAXaEd6x3RtgQm6Dc9RI4ZbxRXZ5svs/QykfG3Y9i28FlZ6KXZ3uL6psQWs0Fkyy6mJnb1S4MYEghnN2+aUwYaQwxPgp78YAQLdfm6suHRqsAcaO5KVc0uq2fvxMpm0DLpQEgYPcvcN1IrjFkBwI4h7o47hFJ/8Kcqu/s6MVDEPPV6iAhWz49dDVle+mlCK8wUSBbHskFVhJczjl8Vv7dxbV4CvlkB4sdz800AB7omPChAbAm/rL2OzCR7+HOATYMHF3O8FA8xW5dl7CThohiClTuM1cQEewIl2WWKSP/v0TazbNnCvS0VYLuPEqJt1cFXG7vI/FxKQTHMlkYZzb+BGPkavc86Y9Y5kPv0FG4nSo7dOoqbjS3I50zn+Wf7Mi+RbgjT5AP1FoqH4GAyPNAQ2woWyuFuC4cM/JjSJzVfx10qEDPvk/EdosRDGW0MaweRGpp76zrVQciR3MzX5VMMCefVyh6oPWOhR9fx1uFh77cz7QEx4EHGL09eiHhSUnkRe0qYWCYAtuZJx3LvMB/hpuOPp5rcdi7+ZuE+EcrxGOCJmnPrH7iekTo8MivaBaI7bGeYBCygGq1bCJkeN7IgSOkRSZSQfZBxBWMvSE/YJ+wHQlkchjba5ytbt3Sd9H3zl493RdJCUiTVj/l0TLK2BJKzmV7pjg/fLl
  template:
    metadata:
      creationTimestamp: null
      labels:
        cephfs-mount-user: dmp-roadmap-locales-user
      name: cephfs-locales-key
      namespace: dmp-roadmap-staging
    type: Opaque
