---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cephfs-uploads-key
  namespace: dmp-roadmap-staging
spec:
  encryptedData:
    key: AgDvkpNWO9m8wk/Fyki4aWmhHwDgUPPl/3ACQSG3EStnmtJofwE8o+/hy0x9xpx2AB09PLQb0dNiNem5RAkdksz40MavUKfl9cTHhUZK9Arqjni4BxfGShQkU+GD2z97JcpfngcTuvGQTAB/XxfWA5BlLupvKsrQDxmr8m+AXCj9FcoxkWThxdLUi0gzYh0GiFJykZFWmgofZB8b120e6Uw9CHLGSp8ZkpmCc4qpGCOOhX55aKvXLwcFqZ2TLyCqJuJzlHzhQhr1uzDZrCTER486ExmPjxrNFCyaztfLxMPYR1ii9CWAbTnuQfSBX42+++SPL3azgbJeFnprC5RKmTAJXIvxKKYdChPhzMuJ7NfDtnASD5KRenCDR0NsimLFpfva/q3lEbO3HoQu+Zqx5RsLu9xzSa1jNbiCl5Zms93ne22pclDN+hScI7ch4SPSCRztpiX+LkLY78B8HVyAUiI7T+7YMK76U8HlM0TkBOvwGK2q/yEwz/T954jU2SHesBUW9SmZVPrCt9aldnqpBKXsxvdrUOkTALru1ZdFkQqMGrkPt6DaeK9WM81RXazUslT8eeGwpmhK780vrYilANa7rWG/nZkPcwHjf2/8If1M+FOp4J1QKgjw7l5OAV/rJIBY+CheFalTOi9Em7rCrAY0f/9GYK18zUwLwFYr8GdkHNwiGrMuXGFhsEa4mCSuoJnjnV0GQspdzToEUdMR8dlTL5eeSkzauRI2Mb4UwiMwo0E+a3HO8BQl
  template:
    metadata:
      creationTimestamp: null
      labels:
        cephfs-mount-user: dmp-roadmap-uploads-user
      name: cephfs-uploads-key
      namespace: dmp-roadmap-staging
    type: Opaque
