global:
  domain:
    prefix: dev
app:
  image:
    tag: "4.4.0-dev.1-app"
assets:
  image:
    tag: "4.4.0-dev.1-assets"
ingress:
  annotations:
    cert-manager.io/issuer: letsencrypt-dev-cloudflare
storage:
  cephfs:
    volumes:
      locales:
        path: "/volumes/_nogroup/a2b85f14-843e-40fe-a6b0-8c4d895312f2"
      uploads:
        path: "/volumes/_nogroup/b2f2d190-3db0-4ada-96db-e05d000e4af0"
config:
  # -- Mailer and SMTP settings
  mailer:
    # -- From address for emails
    from: noreply@dmp-pgd.ca
    # -- To address for system emails
    to: dmp-assistant@tech.alliancecan.ca
    # -- SMTP server address
    smtpAddress: mail-relay-east.computecanada.ca
    # -- SMTP domain
    smtpDomain: dmp-pgd.ca
  environment:
    rollbarEnv: arbutus-dev
