{{- if and .Values.ingress.certManager.enabled .Values.ingress.certManager.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.ingress.certManager.rbac.roleName | default (printf "%s-cert-policy" (include "dmp-roadmap.fullname" .)) }}
  labels:
    {{- $_ := set . "component" "cert-manager-rbac" }}
    {{- include "dmp-roadmap.labels" . | nindent 4 }}
  {{- with .Values.ingress.certManager.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [policy.cert-manager.io]
    resources: [certificaterequestpolicies]
    verbs: [use]
    resourceNames:
      {{- if .Values.ingress.certManager.rbac.policyNames }}
      {{- toYaml .Values.ingress.certManager.rbac.policyNames | nindent 6 }}
      {{- else }}
      - {{ .Values.ingress.certManager.certificateRequestPolicy.name | default (printf "%s-cert-policy" (include "dmp-roadmap.fullname" .)) }}
      {{- end }}
{{- end }}
