apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dmp-roadmap.fullname" . }}-app
  labels:
    {{- $_ := set . "component" "app" }}
    {{- include "dmp-roadmap.labels" . | nindent 4 }}
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- $_ := set . "component" "app" }}
      {{- include "dmp-roadmap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/app/configmap.yaml") . | sha256sum }}
        {{- with .Values.app.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- $_ := set . "component" "app" }}
        {{- include "dmp-roadmap.labels" . | nindent 8 }}
        {{- with .Values.app.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.app.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.priorityClassName | default .Values.global.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "dmp-roadmap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.app.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository | default .Values.global.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default .Values.global.image.imagePullPolicy .Values.app.image.imagePullPolicy }}
          env:
            {{- with (concat .Values.global.env .Values.app.env) }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "dmp-roadmap.fullname" . }}-app-config
            {{- if .Values.app.envFrom }}
            {{- toYaml .Values.app.envFrom | nindent 12 }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.app.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.targetPort }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /api/v1/heartbeat
              port: {{ .Values.app.service.targetPort }}
            periodSeconds: {{ .Values.app.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.app.startupProbe.failureThreshold }}
            successThreshold: {{ .Values.app.startupProbe.successThreshold }}
          livenessProbe:
            httpGet:
              path: /api/v1/heartbeat
              port: {{ .Values.app.service.targetPort }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.app.livenessProbe.successThreshold }}
          readinessProbe:
            httpGet:
              path: /api/v1/heartbeat
              port: {{ .Values.app.service.targetPort }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.app.readinessProbe.successThreshold }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          volumeMounts:
            {{- include "dmp-roadmap.volumeMounts" . | nindent 12 }}
            # Required tmp directories for Rails
            - name: rails-tmp
              mountPath: /usr/src/app/tmp
            {{- with .Values.app.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- include "dmp-roadmap.volumes" . | nindent 8 }}
        # Tmp directories required for Rails
        - name: rails-tmp
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: rails-tmp
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 500Mi
        {{- with .Values.app.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
