---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cephfs-locales-key
  namespace: dmp-roadmap-prod
spec:
  encryptedData:
    key: AgA7ds/ImTqxqc6tKwRMAI1UZwklYvQ56mufM/Gr/IBDDTp2ez0OUHvqYFTbohxoT8/P0zhu11xpVWGyNI+1s8o3puBmmqgjSIoTi8MwWY/XwKxmCf5eVriNaaK0/Rhvg414+In/l0QLSkcwn3hj2sFasHZAW5LoxMIOyjB0NsgfzetJX1Ok6TrINga0G+lLiWIOIh6sBcUGN09EabFsZntfBpxxYndtqtAsawuSzjuDCZ1lSkUZdVtt98vX6/wflADd8ibIgo5+5nfkESGm4hn8SQqF2Ei5TdE6fw342EvwY5o7HRPijRFZ7e2fcrhVGFwZKzXHrinN7OnxZdkPQ8UYcoQD4p3BPd0qQr0yuok50osPi3TNUjMrB1aIwjzkKrnYR0A/8IrKtkem8LuJCnTfTZbo9FXt5KBatkqKAXr/5+Nm/QNKE6p0BskCMoZoCPAz0s/LwaM2XNjpK5Y6TbFJHnFxUjbT0eGthPlXeknW6cWgp5daIwMU0mh8+/ddXubGmAEclaPACQfIxGJN8hQIohHJgHQr1ReSBdGWT7wgpdYGtxxCVij917SgoVkhdFZTqnihbTNhWDkm1wveD/NLlSdCr3YPOXFmae0f/M5C2rIcKRqcKyI+hGn9ayqQ6GU5AJOM1Hxciz2VajG2lbchhHSF18m5/qp2bzapG613ZSKgP7HIrHleCAHxqCrklNfQ1jx5AkQuJ0b0teh7kyYrJk+YGtqB5arH1gHsySh6T9mwBF9MmXPZ
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
        cephfs-mount-user: dmp-roadmap-prod-locales-user
      name: cephfs-locales-key
      namespace: dmp-roadmap-prod
    type: Opaque
