---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cephfs-uploads-key
  namespace: dmp-roadmap-prod
spec:
  encryptedData:
    key: AgCRVQfg/jHIOBhY8a3gEpZS+WAIToj9hX+neowuYOkRB11kwxtCt5UEw/fqVZlXrZXB1MgAwBXef6sKYhkmfYoUgPqfTR5roAWWRz3QnHIjY9sBQudIccLRiDvOKxZbeGXgae76kk8OfF3GRDwSzo2f5dET+YWeFZQmhhgUP9hkj+nW9HoDUhHCy+g5vDJvMN1Y10DDsN9H3Y83+PUMbw3roCMiruz+aEou7yr32ZxWC98F547VT/QWXi4qb4nkYV+xA1O3i2kfDYIq/yAXh1r1SgQbrugIk6TpeCHjUDp2PTaOCoAI02QaFb5suWKpECEjMB1XVGsAIXQv0RZJT9ifOUasyVN5oZyocVJKlqtpRy6hCsBNRBZ0KMkCsyi4hxBawoPpBOWb38pLVF6Dra3JBWIlQgBWhsCYE52UX6RMZvbYiHMpTwp2DUm9ZUAtnQ33x3FzsBXtkm5t4jWpSQvuWR8219k0KROaXlG82tlTBqn4foO9F7cSccbbmGOGZyg7Vd7zBPQ7uygIy+KTzini/xp4LojNsLoq4dnYVtmUvjO2EHv/ZMmOEqz7AmXQc1TuTKgM9a9SjCY6YWDrex/yzM/tqZfW6Vs8UY9ozD5iQutm1nZp/PiJI7QZnzxtbQR6w4IaLUGjsTnRhsGmahs3F3zHCWxkXG3jmoNDfBxKligKW5jLWqCnbyC7Tf3cLUfausiSqoSY43apaow9tbdWUWZZ2ua7rZA9jkxaZ9XfQttiCpDuqu4A
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
        cephfs-mount-user: dmp-roadmap-prod-uploads-user
      name: cephfs-uploads-key
      namespace: dmp-roadmap-prod
    type: Opaque
