---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cephfs-locales-key
  namespace: dmp-roadmap-prod
spec:
  encryptedData:
    key: AgCi2/Ls0hYYu0BGGtptxwDR83tJJ5xxY5Cc7ZV42B+PKwcDTVSczAtSFo63yZG4uF3W6xQ0F7OdezmK0Q0JhH8/W4HSPXD95JZ9PMA6tyW/+WFN6jkjphepCijwbBkBm5kq88oRyJAEm6fJbaR1W3k2uep59fKvPsTWuFpOEqsSFBZ4O7M/GbyiGqeT7hktDWGSsG3PV+NOu3WUAcDPLKOpTDXnadbSnCPxVNGFCAgxnZ978OOcwW3VOpjB4mYfPUaVOHT5UJQpem6YYg97cLK5zETIVvGUlA6R9s46V+cl9gbhmG/VG2HmWLC49qLYXmHmdBqGI5OTv9bJvLcYA0oCXl59HNGgD5QwoyzVsC6m6fKhauhxkRNDOaohzkbMBhk3votD47uTtslIbfJILodhtagdjxlebe0xazJxOwLXgHIv9LxjXlHAiXo2wdZyHfzqNsnvMAUL9qRx5QmJEqQN80vHHhZq2a5b0gSD2IfuM6knTK53zk3ijQr4xoIYCueGBHGzLzJeFB7/iEwt1Eiz4coxo20waQ8Dq1kSfFh7VexyS6Lpi7VBaEbeeOo26ffVkAC2BLi/+Awf7yxxpL0J7UhBps7xsmNVJFPZnzFThNt1o77wyAGJOg783gBFtpT2mUznEHFuxJFNp9Ld2kbyB8WLp3kKVYPJrWdD/vOopzivKhEbwiQckMPkJYWDYPoLS8ZvvO64FJ5HF8JNVGiL+TRtHJ7Ji+9bsDYeAxlfA67gD4I98VSd
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
        cephfs-mount-user: dmp-roadmap-prod-locales-user
      name: cephfs-locales-key
      namespace: dmp-roadmap-prod
    type: Opaque
