---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cephfs-locales-key
  namespace: dmp-roadmap-prod
spec:
  encryptedData:
    key: AgDnoRqTsXrXKSBuoYcAkc/zOSCR1m1vdMyIUMIM27pPI7IR35hZV4gSXc8UkMtr0yXHanXg/LbiDgZLEvz3bHwNMn4Y6NuwM0HUPHASkqNlcN6jTmRgCdwX04ybq3sX2HjXlbGbX5pZ5boCszSf0sCCdsDbTC71kgFiHIzkEo2WMpSim+oIV4l40DG6TmFfHfj/O+npB4qoYkoOQKWRlmcudFbOMz17vCoNWP5A4BerMD1AbJxdeguxBKsQrIP4kFRS9dhbrhHWsuP1n4A4MMzBbPa+MooklivAJfJeiHzwYsBai18N7qTbSXnBW8qFAtVMbAQRyv8eUyUwdp1tnpiiqT9OUe1JZv6yZIpkQ5oQ68+ugYNSji1VYbcd6/rMQJ973yGJj2KQeT98b+xG5zTC87QwJJDM+z9xH7IzFSyYwFVG6kdon5QnO/P5FHKw3VxmeB3JEeBmCuMjJsxzA6ArEEOMLzfK+37jJU+vtQQO6+YEMSHjQT144Pq8O9jm4EbchbGllBbMlkaDlHGyNn1Ao1pIiAhpB17O0H+aoFCqhMybHbVTbcLHD1LXZ48sIF2/Ez6vrLdlCuW+teQdWzfw3uM79a9k7HaWN4lpCGOgmKhGzUnn2cPiaMrwmQqlZgWyQXLZbkVGwvpukp83RGk2kKmoMzVhHfF4XsScftUfmQLniRxhzmCrY4VxiiQwKcT2Kor174Dw0um5utD74vjAgGEcK94gazZA0WH60W6Ogoqn9wFo9Yc3
  template:
    metadata:
      creationTimestamp: null
      labels:
        cephfs-mount-user: dmp-roadmap-locales-user
      name: cephfs-locales-key
      namespace: dmp-roadmap-prod
    type: Opaque
