---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cephfs-uploads-key
  namespace: dmp-roadmap-prod
spec:
  encryptedData:
    key: AgBV0fz2iGzausE3x7XQRyhJ/rml14qRkvKXDt4LmTQ8cTAH8soNm9ZPWZWcNT9iRGFW/2tRxGhcW3YeVveAjI5LiUQH2VFlyVW1/480mrw1G+81BBW5IgWTrGy8uY815mhYrKc5eSi29ozkcPfG16gU9OS6yy6d8kjxHIinjV6SWpgbQpf+r0UuI1fcqPbkKiuH0CmzfFAhTd0tT9p+5x/3W5X85QKEfVX9TJVf4HI/cs9eCPNa52mpikJP4PZG2JdI6V0KPpEjcqkbTK8yZVds2uzRtvrG0eWCNthdDztEapuEQLHSItucriOhrwV8Wis2DttjFqngYnO9P4qTiRegqxT2nvMrMNyBmmEVJ2SALcRkAY5Er82hDd8fhR+NIVna/g0Ul13kBPQnebMnKcuj+DyMPqmlyBjXDAqZPq+bElwBVblAj8p02NR4R7OadN71ct+7YULNt6PxLUcDJ35cGZnpvVtUod9bbOXUYXP8bhubvRj5FPPej6VnFrAhWQ+yHkwX5H/duQ836BRFQ9MOjPZlOVFN0B3J4jEX1kpKQ6DuNMUh2dVOPfvRz+YzRLvTsHz06CeQ7fK4AtmyzazujDDur9xOf4yoCbT/x0xEpCJsYFJJObvh7W1DhE02ax6yaMXvaGy4SQCXqnX6d+vTXma2exqyLHTC6tveC5YAIqBJzWTky6G3mjULEmfQ+QDgAfkMXjhAgwswGXl9thCicUncuj0/e3rdp3udsPxL0mRBPkTI7Go0
  template:
    metadata:
      creationTimestamp: null
      labels:
        cephfs-mount-user: dmp-roadmap-uploads-user
      name: cephfs-uploads-key
      namespace: dmp-roadmap-prod
    type: Opaque
