{{- if .Values.assets.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dmp-roadmap.fullname" . }}-assets
  labels:
    {{- $_ := set . "component" "assets" }}
    {{- include "dmp-roadmap.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dmp-roadmap.fullname" . }}-assets
  minReplicas: {{ .Values.assets.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.assets.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.assets.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.assets.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.assets.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.assets.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
