# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ deployment-portage ]
  pull_request:
    branches: [ deployment-portage ]

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: roadmap_user
          MYSQL_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD:  ${{ env.ROOT_DATABASE_PASSWORD }}
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - name: Verify MariaDB connection
      uses: actions/checkout@v2
      env:
        PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
          sleep 1
        done
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.8
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake spec
